name: cash_peak
description: "This is a financial application designed for better expense tracking."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  hive_ce:
  hive_ce_flutter:

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator:
  build_runner:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cashpeak.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
